CREATE TABLE "podcasts"(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  event_description TEXT,
  date_created DATE DEFAULT now() NOT NULL,
  media_runtime TEXT NOT NULL,
  release_date TEXT DEFAULT NULL,
  genre TEXT DEFAULT NULL,
  imdb_rating TEXT DEFAULT NULL,
  mpaa_rating TEXT DEFAULT NULL,
  poster TEXT DEFAULT NULL
);