CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  user_comment TEXT NOT NULL,
  user_name TEXT REFERENCES user(username) ON DELETE SET NULL NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE movies
  ADD COLUMN
    comment_id INTEGER REFERENCES comments(id) ON DELETE SET NULL NOT NULL;

ALTER TABLE tv_shows
  ADD COLUMN
    comment_id INTEGER REFERENCES comments(id) ON DELETE SET NULL NOT NULL;

ALTER TABLE podcasts
  ADD COLUMN
    comment_id INTEGER REFERENCES comments(id) ON DELETE SET NULL NOT NULL;

ALTER TABLE books
  ADD COLUMN
    comment_id INTEGER REFERENCES comments(id) ON DELETE SET NULL NOT NULL;